### ISSUE TITLE
add an option to only verify changes made since a particular date

### ISSUE THREAD

**Issue by toejough** [openlyinc/openlynt#2]
similar to what golangci-lint has.  Especially as new cool rules become available, we'll want to be able to limit how far back in time the code is validated.  Nobody wants to enable a new cool rule if they also have to fix 100+ violations.

I'm not sure how golangci-lint does it, but I'm imagining a workflow like:

* Identify the failures, with their lines
* Identify the lines changed since a given date
* only report the failures on the changed lines.

**Comment by chrsm** [comment]
`golanglint-ci` uses their own fork of `revgrep` internally: [source](https://github.com/golangci/golangci-lint/blob/8fceb7fc4797c9552b8fd3d1d91ac0b0209ed429/pkg/result/processors/diff.go)

I will look into using the `revgrep` library soon.

**Comment by chrsm** [comment]
Naive impl at [pr#4](https://github.com/openlyinc/openlynt/pull/4). I'll chat with you about it tomorrow.
